### PR TITLE
Add Laravel 7 support

### PR DESCRIPTION
**Pull request by Lloople**
```
> Executing task: /Users/lloople/Code/dark-sky-api/vendor/bin/phpunit <

PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.14
Configuration: /Users/lloople/Code/dark-sky-api/phpunit.xml.dist

...............................................................  63 / 380 ( 16%)
............................................................... 126 / 380 ( 33%)
............................................................... 189 / 380 ( 49%)
............................................................... 252 / 380 ( 66%)
............................................................... 315 / 380 ( 82%)
............................................................... 378 / 380 ( 99%)
..                                                              380 / 380 (100%)

Time: 208 ms, Memory: 12.00 MB

OK (380 tests, 433 assertions)
```

### CODE REVIEW

**Comment by dmitry-ivanov** [comment]
@Lloople Hey David,

Thanks for your contribution!

There's a problem - Travis [build fails](https://travis-ci.com/dmitry-ivanov/dark-sky-api/jobs/295303231) on PHP 7.1.

It looks like there's a problem related to "vlucas/phpdotenv" on version 4 for that build...

**Comment by Lloople** [comment]
I see...
Any idea how can this be resolved? I have no clue for the moment 🤔

**Comment by dmitry-ivanov** [comment]
I think there's an unexpected combination of Laravel + DotEnv versions happening on PHP 7.1 now... I'll take a look when I'll have a moment for that.

**Comment by dmitry-ivanov** [comment]
Laravel 7 support added in [1.2.0](https://github.com/dmitry-ivanov/dark-sky-api/releases/tag/1.2.0).

**Pull request closed without merging**
